[build]
  command = "npm run build"
  # 👇 use "build" if React, use "dist" if Vite
  publish = "build"

[dev]
  command = "npm start"
  port = 3000
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
